FROM cgr.dev/chainguard/wolfi-base

RUN apk update && apk add ca-certificates-bundle build-base openssh go-1.20~=1.20.4

ENV GODEBUG=tarinsecurepath=0,zipinsecurepath=0

ENTRYPOINT /usr/bin/go

CMD help
