name: Build
on: [push]

jobs:
  build:
    runs_on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: chainguard-images/actions/apko-build@main
        with:
          config: apko.yaml
          tag: test:test
          archs: x86_64
